#!/usr/bin/env python3
"""Generator: YAML-Datenelemente → FHIR Logical Model (FSH-Form).

Projekt-agnostisch wiederverwendbar: das eingebettete Schema (BaseDataElement
Logical Model + 10 generische CodeSystems/ValueSets) ist domänen-neutral
formuliert; nur die URL-Basis (`--namespace-base`) und der Logical-Model-Title
(`--title`) sind projekt-spezifisch parametrisierbar.

Trennung Struktur / Inhalt:
  - STRUKTUR (im Skript embedded, reusable):
      Logical Model 'BaseDataElement' (EHDS-Pattern: kind=logical,
      Parent=Base, alle Felder als reguläre Sub-Elemente, KEINE Extensions);
      10 CS/VS für Phase, Tumorentität, Datentypen, Binding-Status, Standards,
      ISO 13972 Type, ISO 13972 Publication Status (8 Werte), Guideline Source,
      Recommendation Grade, Relation.
  - INHALT (aus elements/<phase>/*.yaml, projekt-spezifisch):
      konkrete Datenelement-Instanzen mit Codes, Labels, Quellen, Mappings.

Aufruf:
  python scripts/build-fhir-logical-models.py
  python scripts/build-fhir-logical-models.py --out /pfad/zu/zielordner
  python scripts/build-fhir-logical-models.py \\
      --namespace-base https://example.org/data-elements/fhir \\
      --title "MyProject Data Element Specification"

Erzeugte Struktur:
  <out>/
  ├── _schema/
  │   ├── base-data-element.fsh        ← Logical Model
  │   └── codesystems-valuesets.fsh    ← CodeSystems + ValueSets
  └── instances/
      ├── <phase>/
      │   └── <name>.fsh                ← Instance of BaseDataElement
      └── ...

Voraussetzungen:
  pip install pyyaml
  (FHIR-Validierung optional via Sushi — nicht hier integriert.)
"""
from __future__ import annotations

import argparse
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
ELEMS = ROOT / "elements"

# ============================================================================
# EMBEDDED SCHEMA — Logical Model + CodeSystems + ValueSets
# Quelle der Wahrheit für das FHIR-Schema. Bei Schema-Änderungen hier pflegen.
# ============================================================================

LOGICAL_MODEL_FSH = '''// =====================================================================
// BaseDataElement — projekt-agnostisches FHIR Logical Model
// EHDS-Pattern: kind=logical, derivation=specialization, baseDefinition=Base.
// Alle Attribute als reguläre Sub-Elemente (BackboneElement / FHIR-Datentypen).
// Keine Extensions. Projekt-spezifisch ist nur der Title (via --title).
//
// Auto-generated by scripts/build-fhir-logical-models.py
// Quelle: elements/<phase>/*.yaml — Single Source of Truth.
// =====================================================================

Logical: BaseDataElement
Id: base-data-element
Title: "MiHUB Patientenpfad — Datenelement-Spezifikation"
Description: """
Schema für die strukturierte Erhebung von Datenelementen entlang des onkologischen
Patientenpfads (Lungenkarzinom). Strukturiert gemäß ISO 13972:2022 §6+§7 (CIM)
und ISO 13606-2 §6.2 (Archetyp-Governance), kompatibel mit HL7 HSRA und nationalen
wie internationalen Implementation Guides (oBDS, MII KDS, KBV MIO, gematik ePA,
mCODE, OMOP CDM u. a.).
"""
Parent: Base
Characteristics: #can-be-target

// --- Identifikation -------------------------------------------------
* identifier 1..1 string "Stabiler, lesbarer Identifier" "Konvention: mihub.lung.<phase>.<element>.v<major>.<minor>"
* uuid 0..1 string "Globally unique identifier (UUID)"
* name 1..1 string "Technischer camelCase-Name"
* labelDe 1..1 string "Deutsche Anzeigebezeichnung"
* labelEn 0..1 string "Englische Anzeigebezeichnung (optional)"
* definitionDe 1..1 markdown "Klinisch-semantische Definition"
* definitionEn 0..1 markdown "Englische Definition (optional)"

// --- Versorgungs-Kontext --------------------------------------------
* phase 1..1 code "Versorgungsphase"
* phase from PhasesVS (required)
* tumorEntity 1..* code "Tumorentität"
* tumorEntity from TumorEntityVS (extensible)

// --- Datentyp & Kardinalität ---------------------------------------
* dataType 1..1 code "Datentyp gemäß ISO 21090 / FHIR R4"
* dataType from DataTypesVS (required)
* cardinality 1..1 string "FHIR-Kardinalität (Pattern: [01*]..[1*])"
* unit 0..1 code "UCUM-Einheit (nur bei Quantity-/numerischen Datentypen)"

// --- Wertebereich / Binding ----------------------------------------
* valueSet 0..1 BackboneElement "Wertebereich / Binding"
* valueSet.bindingStrength 1..1 code "FHIR-Binding-Strength"
* valueSet.bindingStrength from http://hl7.org/fhir/ValueSet/binding-strength (required)
* valueSet.standardBindingStatus 1..1 code "Status der semantischen Standardbindung"
* valueSet.standardBindingStatus from BindingStatusVS (required)
* valueSet.uri 0..1 uri "ValueSet-URL"
* valueSet.notes 0..1 markdown "Begründung bei standardBindingStatus=no-standard-found"
* valueSet.coding 0..* Coding "Beispielhafte Codings"

// --- Multi-Standard-Mappings ---------------------------------------
* standardMapping 0..* BackboneElement "Mappings auf etablierte Standards"
* standardMapping.standard 1..1 code "Standard-Identifier"
* standardMapping.standard from StandardsVS (required)
* standardMapping.profileOrUrl 0..1 uri
* standardMapping.resource 0..1 string
* standardMapping.path 0..1 string
* standardMapping.notes 0..1 string

// --- Anwendungshinweise --------------------------------------------
* instructionDe 0..1 markdown "Erfassungs-/Interpretationshinweis"
* constraintsDe 0..1 markdown "Einschränkungen, Ausschlüsse"

// --- Versorgungsprozess --------------------------------------------
* careProcess 0..1 BackboneElement "Bezug zum Versorgungsprozess"
* careProcess.trigger 0..1 string
* careProcess.frequencyPattern 0..1 string
* careProcess.responsibleRole 0..1 string

// --- Evidenz -------------------------------------------------------
* evidence 0..1 BackboneElement "Evidenzbasis"
* evidence.guidelineReference 0..* BackboneElement "Leitlinien-/Quellen-Referenz"
* evidence.guidelineReference.source 1..1 code
* evidence.guidelineReference.source from GuidelineSourceVS (extensible)
* evidence.guidelineReference.version 0..1 string
* evidence.guidelineReference.section 0..1 string
* evidence.guidelineReference.recommendationGrade 0..1 code
* evidence.guidelineReference.recommendationGrade from RecommendationGradeVS (extensible)
* evidence.guidelineReference.evidenceLevel 0..1 string
* evidence.guidelineReference.url 0..1 uri

// --- ISO 13972 Metadaten ------------------------------------------
* metadata 1..1 BackboneElement "ISO 13972 Metadaten"
* metadata.type 0..1 code
* metadata.type from Iso13972TypeVS (required)
* metadata.keyword 1..* string
* metadata.author 1..* string
* metadata.endorsingAuthority 1..1 string
* metadata.versionNumber 1..1 string
* metadata.creationDate 1..1 date
* metadata.publicationDate 0..1 date
* metadata.expirationDate 0..1 date
* metadata.nextRevisionDate 0..1 date
* metadata.publicationStatus 1..1 code "ISO 13972 PublicationStatus (alle 8 Werte)"
* metadata.publicationStatus from Iso13972PublicationStatusVS (required)
* metadata.publisher 1..1 string
* metadata.language 1..* code
* metadata.license 0..1 string

// --- Provenance ----------------------------------------------------
* provenance 1..1 BackboneElement "Bearbeitungs-Audit"
* provenance.createdBy 1..1 string
* provenance.reviewer 0..* string
* provenance.gitCommit 0..1 string

// --- Issues + Beziehungen ------------------------------------------
* issue 0..* markdown "Offene Diskussions-/Reviewpunkte"
* relatedElement 0..* BackboneElement "Beziehung zu anderen Datenelementen"
* relatedElement.relation 1..1 code
* relatedElement.relation from RelationVS (required)
* relatedElement.target 1..1 string
'''

VALUESETS_FSH = '''// =====================================================================
// CodeSystems + ValueSets für das BaseDataElement Logical Model.
// Strukturen sind projekt-agnostisch; Codes (z. B. #followup, #palliative)
// sind aktuelle Projekt-Inhalte und können in einem anderen Projektkontext
// erweitert oder ausgetauscht werden.
// Auto-generated by scripts/build-fhir-logical-models.py
// =====================================================================

// --- Versorgungsphasen ---------------------------------------------
CodeSystem: PhasesCS
Id: phases
Title: "Care Pathway Phases"
* ^url = "{NAMESPACE_BASE}/CodeSystem/phases"
* ^version = "0.1.0"
* ^status = #draft
* ^content = #complete
* #followup "Onkologische Nachsorge nach kurativer Therapie"
* #surveillance "Verlaufsbeobachtung unter Systemtherapie"
* #palliative "Palliativversorgung"
* #screening "Prävention / Früherkennung (geplant)"
* #diagnostics "Diagnostik & Staging (geplant)"
* #treatment "Therapie kurativ + palliativ (geplant)"
* #rehabilitation "Rehabilitation (geplant)"
* #transition "Sektorenübergang (geplant)"

ValueSet: PhasesVS
Id: phases-vs
Title: "Care Pathway Phases — ValueSet"
* ^url = "{NAMESPACE_BASE}/ValueSet/phases"
* include codes from system PhasesCS

// --- Tumorentität --------------------------------------------------
CodeSystem: TumorEntityCS
Id: tumor-entity
Title: "Tumor Entities"
* ^url = "{NAMESPACE_BASE}/CodeSystem/tumor-entity"
* ^content = #complete
* #NSCLC "Nicht-kleinzelliges Lungenkarzinom"
* #SCLC "Kleinzelliges Lungenkarzinom"
* #lung_cancer_any "Lungenkarzinom unspezifisch / beide"

ValueSet: TumorEntityVS
Id: tumor-entity-vs
* ^url = "{NAMESPACE_BASE}/ValueSet/tumor-entity"
* include codes from system TumorEntityCS

// --- Datentypen ----------------------------------------------------
CodeSystem: DataTypesCS
Id: datatypes
* ^url = "{NAMESPACE_BASE}/CodeSystem/datatypes"
* ^content = #complete
* #boolean "boolean"
* #code "code"
* #Coding "Coding"
* #CodeableConcept "CodeableConcept"
* #Quantity "Quantity"
* #Range "Range"
* #Ratio "Ratio"
* #integer "integer"
* #decimal "decimal"
* #string "string"
* #text "text"
* #date "date"
* #dateTime "dateTime"
* #Period "Period"
* #Reference "Reference"
* #Attachment "Attachment"
* #Annotation "Annotation"

ValueSet: DataTypesVS
Id: datatypes-vs
* ^url = "{NAMESPACE_BASE}/ValueSet/datatypes"
* include codes from system DataTypesCS

// --- Standard-Binding-Status ---------------------------------------
CodeSystem: BindingStatusCS
Id: binding-status
* ^url = "{NAMESPACE_BASE}/CodeSystem/binding-status"
* ^content = #complete
* #mapped "Mind. ein Coding stammt aus einer etablierten Terminologie"
* #no-standard-found "Kein passender Standard gefunden — Codes sind projekt-lokal"
* #pending-mapping "Standard existiert, Mapping ausstehend"
* #n-a "Datentyp benötigt keine Codierung"

ValueSet: BindingStatusVS
Id: binding-status-vs
* ^url = "{NAMESPACE_BASE}/ValueSet/binding-status"
* include codes from system BindingStatusCS

// --- Standards-Liste -----------------------------------------------
CodeSystem: StandardsCS
Id: standards
* ^url = "{NAMESPACE_BASE}/CodeSystem/standards"
* ^content = #complete
* #obds "Onkologischer Basisdatensatz §65c SGB V (DE)"
* #gekid-adt "ADT/GEKID-Tumorbasisdokumentation (DE, historisch)"
* #gematik-epa-fhir "gematik ePA für alle FHIR IGs (DE)"
* #gematik-erezept-fhir "gematik eRezept FHIR IG (DE)"
* #kbv-mio "KBV MIO-Bundles (DE)"
* #fhir-mii-kds "MII Kerndatensatz (DE Forschung/FDPG)"
* #fhir-isik "gematik ISiK (DE KIS/AIS)"
* #fhir-r4-base "FHIR R4 Vanilla"
* #fhir-genomics "HL7 FHIR Genomics IG"
* #mcode "HL7 minimal Common Oncology Data Elements IG"
* #openehr-archetype "openEHR Archetyp/Template"
* #omop-cdm "OHDSI OMOP Common Data Model"
* #cdisc-sdtm "CDISC SDTM/CDASH"
* #hl7-v2 "HL7 V2"
* #dicom-sr "DICOM Structured Report"
* #hl7-cda "HL7 CDA"
* #ihe-xds "IHE XDS Affinity Domain"
* #other "Sonstige (Erläuterung in notes)"

ValueSet: StandardsVS
Id: standards-vs
* ^url = "{NAMESPACE_BASE}/ValueSet/standards"
* include codes from system StandardsCS

// --- ISO 13972 Type ------------------------------------------------
CodeSystem: Iso13972TypeCS
Id: iso13972-type
* ^url = "{NAMESPACE_BASE}/CodeSystem/iso13972-type"
* ^content = #complete
* #observation "Beobachtung"
* #procedure "Prozedur"
* #evaluation "Bewertung / Outcome"
* #plan "Plan / CarePlan"
* #condition "Diagnose / Condition"
* #medication "Medikation"
* #social "Sozialanamnese"

ValueSet: Iso13972TypeVS
Id: iso13972-type-vs
* ^url = "{NAMESPACE_BASE}/ValueSet/iso13972-type"
* include codes from system Iso13972TypeCS

// --- ISO 13972 Publikationsstatus (alle 8 Werte!) -----------------
CodeSystem: Iso13972PublicationStatusCS
Id: iso13972-publication-status
* ^url = "{NAMESPACE_BASE}/CodeSystem/iso13972-publication-status"
* ^content = #complete
* #AuthorDraft "AuthorDraft — offene Bearbeitung"
* #CommitteeDraft "CommitteeDraft — Konsultation"
* #Submitted "Submitted — eingereicht"
* #ApprovedForTesting "ApprovedForTesting — Pilotierung"
* #ApprovedForProductionUse "ApprovedForProductionUse — produktiv"
* #Withdrawn "Withdrawn — zurückgezogen"
* #Superseded "Superseded — durch neuere Version ersetzt"
* #Rejected "Rejected — abgelehnt"

ValueSet: Iso13972PublicationStatusVS
Id: iso13972-publication-status-vs
* ^url = "{NAMESPACE_BASE}/ValueSet/iso13972-publication-status"
* include codes from system Iso13972PublicationStatusCS

// --- Leitlinien-Quellen --------------------------------------------
CodeSystem: GuidelineSourceCS
Id: guideline-source
* ^url = "{NAMESPACE_BASE}/CodeSystem/guideline-source"
* ^content = #complete
* #s3-ll-lungenkarzinom "S3-LL Lungenkarzinom"
* #s3-ll-palliativ "S3-LL Palliativmedizin"
* #s3-ll-tabakentwoehnung "S3-LL Tabakentwöhnung (AWMF 076-006l)"
* #onkopedia-nsclc "Onkopedia NSCLC"
* #onkopedia-sclc "Onkopedia SCLC"
* #ocp-lung "Optimal Care Pathway (AU)"
* #ag-lonko "AG LONKO / Survivorship"
* #esmo "ESMO Clinical Practice Guidelines"
* #asco "ASCO Guidelines"
* #other "Sonstige Quelle"

ValueSet: GuidelineSourceVS
Id: guideline-source-vs
* ^url = "{NAMESPACE_BASE}/ValueSet/guideline-source"
* include codes from system GuidelineSourceCS

// --- Empfehlungsgrade ----------------------------------------------
CodeSystem: RecommendationGradeCS
Id: recommendation-grade
* ^url = "{NAMESPACE_BASE}/CodeSystem/recommendation-grade"
* ^content = #complete
* #A "Grad A — soll-Empfehlung"
* #B "Grad B — sollte-Empfehlung"
* #0 "Grad 0 — kann-Empfehlung"
* #EK "EK — Konsensbasierte Expertenempfehlung"
* #Statement "Statement"
* #n-a "nicht zutreffend"

ValueSet: RecommendationGradeVS
Id: recommendation-grade-vs
* ^url = "{NAMESPACE_BASE}/ValueSet/recommendation-grade"
* include codes from system RecommendationGradeCS

// --- Beziehungstypen -----------------------------------------------
CodeSystem: RelationCS
Id: relation
* ^url = "{NAMESPACE_BASE}/CodeSystem/relation"
* ^content = #complete
* #isPartOf "isPartOf"
* #hasPart "hasPart"
* #specializes "specializes"
* #generalizes "generalizes"
* #dependsOn "dependsOn"
* #supersedes "supersedes"
* #supersededBy "supersededBy"

ValueSet: RelationVS
Id: relation-vs
* ^url = "{NAMESPACE_BASE}/ValueSet/relation"
* include codes from system RelationCS
'''

# ============================================================================
# Mapping-Tabellen YAML → FHIR-Codes
# ============================================================================

SYSTEM_URL = {
    "snomed-ct": "http://snomed.info/sct",
    "loinc": "http://loinc.org",
    "icd-10-gm": "http://fhir.de/CodeSystem/bfarm/icd-10-gm",
    "icd-o-3": "urn:oid:2.16.840.1.113883.6.43.1",
    "icf": "http://fhir.de/CodeSystem/bfarm/icf",
    "ops": "http://fhir.de/CodeSystem/bfarm/ops",
    "atc": "http://fhir.de/CodeSystem/bfarm/atc",
    "ucum": "http://unitsofmeasure.org",
    "meddra": "urn:oid:2.16.840.1.113883.6.163",
    "hl7-v3": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
    "kdl": "urn:oid:1.2.276.0.76.5.451",
    "local-no-standard-binding": "{NAMESPACE_BASE}/CodeSystem/local-no-standard-binding",
}

GUIDELINE_SOURCE_CODES = {
    "S3-LL Lungenkarzinom": "s3-ll-lungenkarzinom",
    "S3-LL Palliativmedizin": "s3-ll-palliativ",
    "S3-LL Tabakentwöhnung": "s3-ll-tabakentwoehnung",
    "Onkopedia NSCLC": "onkopedia-nsclc",
    "Onkopedia SCLC": "onkopedia-sclc",
    "OCP Lung (AU)": "ocp-lung",
    "AG LONKO / Survivorship": "ag-lonko",
    "ESMO": "esmo",
    "ASCO": "asco",
}


# ============================================================================
# FSH-Helpers
# ============================================================================

def instance_name(name: str) -> str:
    return name[0].upper() + name[1:]


def fsh_str(s) -> str:
    if s is None:
        return '""'
    s = str(s)
    if "\n" in s or len(s) > 100 or '"' in s:
        return '"""' + s.replace('"""', '\\"""') + '"""'
    return '"' + s.replace('"', '\\"') + '"'


def fsh_code(s) -> str:
    if s is None:
        return "#unknown"
    s = str(s).strip().replace("/", "-")
    return f"#{s}"


# ============================================================================
# Per-Element-Render
# ============================================================================

def render_instance(doc: dict) -> str:
    out: list[str] = []
    yaml_id = doc["id"]
    name = doc["name"]
    inst = instance_name(name)
    md = doc.get("iso13972_metadata") or {}
    label = doc.get("label_de", "")
    definition = doc.get("definition_de", "")

    out.append(f"// Auto-generated from {yaml_id}")
    out.append(f"// Source: elements/{doc['phase'].replace('followup','follow-up')}/{name}.yaml")
    out.append("// FHIR-Form: Instance of Logical Model 'BaseDataElement' (EHDS-Pattern, ohne Extensions)")
    out.append("")
    out.append(f"Instance: {inst}")
    out.append("InstanceOf: BaseDataElement")
    out.append("Usage: #example")
    out.append(f"Title: {fsh_str(label)}")
    out.append(f"Description: {fsh_str(definition)}")
    out.append("")

    out.append(f"* identifier = {fsh_str(yaml_id)}")
    if doc.get("uuid"):
        out.append(f"* uuid = {fsh_str(doc['uuid'])}")
    out.append(f"* name = {fsh_str(name)}")
    out.append(f"* labelDe = {fsh_str(label)}")
    if doc.get("label_en"):
        out.append(f"* labelEn = {fsh_str(doc['label_en'])}")
    out.append(f"* definitionDe = {fsh_str(definition)}")
    out.append(f"* phase = {fsh_code(doc['phase'])}")
    for i, te in enumerate(doc.get("tumor_entity", []) or []):
        out.append(f"* tumorEntity[{i}] = {fsh_code(te)}")
    out.append(f"* dataType = {fsh_code(doc['datatype'])}")
    out.append(f"* cardinality = {fsh_str(doc['cardinality'])}")
    if doc.get("unit"):
        out.append(f"* unit = {fsh_code(doc['unit'])}")

    vs = doc.get("value_set") or {}
    if vs:
        out.append("")
        out.append("// --- ValueSet binding ---")
        out.append(f"* valueSet.bindingStrength = {fsh_code(vs.get('binding_strength', 'example'))}")
        sb = vs.get("standard_binding_status", "mapped")
        out.append(f"* valueSet.standardBindingStatus = {fsh_code(sb)}")
        if vs.get("uri"):
            out.append(f"* valueSet.uri = {fsh_str(vs['uri'])}")
        if vs.get("notes"):
            out.append(f"* valueSet.notes = {fsh_str(vs['notes'])}")
        for i, c in enumerate(vs.get("codings", []) or []):
            sys_url = SYSTEM_URL.get(c.get("system", ""), c.get("system", ""))
            out.append(f"* valueSet.coding[{i}].system = {fsh_str(sys_url)}")
            out.append(f"* valueSet.coding[{i}].code = {fsh_code(c.get('code', ''))}")
            if c.get("display"):
                out.append(f"* valueSet.coding[{i}].display = {fsh_str(c['display'])}")

    sm_list = doc.get("standard_mappings") or []
    if sm_list:
        out.append("")
        out.append("// --- Standard mappings ---")
        for i, sm in enumerate(sm_list):
            out.append(f"* standardMapping[{i}].standard = {fsh_code(sm['standard'])}")
            if sm.get("profile_or_url"):
                out.append(f"* standardMapping[{i}].profileOrUrl = {fsh_str(sm['profile_or_url'])}")
            if sm.get("resource"):
                out.append(f"* standardMapping[{i}].resource = {fsh_str(sm['resource'])}")
            if sm.get("path"):
                out.append(f"* standardMapping[{i}].path = {fsh_str(sm['path'])}")
            if sm.get("notes"):
                out.append(f"* standardMapping[{i}].notes = {fsh_str(sm['notes'])}")

    if doc.get("instruction_de"):
        out.append("")
        out.append(f"* instructionDe = {fsh_str(doc['instruction_de'])}")
    if doc.get("constraints_de"):
        out.append(f"* constraintsDe = {fsh_str(doc['constraints_de'])}")

    cp = doc.get("care_process") or {}
    if cp:
        out.append("")
        out.append("// --- Care process ---")
        if cp.get("trigger"):
            out.append(f"* careProcess.trigger = {fsh_str(cp['trigger'])}")
        if cp.get("frequency_pattern"):
            out.append(f"* careProcess.frequencyPattern = {fsh_str(cp['frequency_pattern'])}")
        if cp.get("responsible_role"):
            out.append(f"* careProcess.responsibleRole = {fsh_str(cp['responsible_role'])}")

    refs = (doc.get("evidence") or {}).get("guideline_references") or []
    if refs:
        out.append("")
        out.append("// --- Evidence ---")
        for i, ref in enumerate(refs):
            src_code = GUIDELINE_SOURCE_CODES.get(ref.get("source", ""), "other")
            out.append(f"* evidence.guidelineReference[{i}].source = {fsh_code(src_code)}")
            if ref.get("version"):
                out.append(f"* evidence.guidelineReference[{i}].version = {fsh_str(ref['version'])}")
            if ref.get("section"):
                out.append(f"* evidence.guidelineReference[{i}].section = {fsh_str(ref['section'])}")
            if ref.get("recommendation_grade"):
                out.append(f"* evidence.guidelineReference[{i}].recommendationGrade = {fsh_code(ref['recommendation_grade'])}")
            if ref.get("evidence_level"):
                out.append(f"* evidence.guidelineReference[{i}].evidenceLevel = {fsh_str(ref['evidence_level'])}")
            if ref.get("url"):
                out.append(f"* evidence.guidelineReference[{i}].url = {fsh_str(ref['url'])}")

    out.append("")
    out.append("// --- ISO 13972 metadata ---")
    if md.get("type"):
        out.append(f"* metadata.type = {fsh_code(md['type'])}")
    for i, kw in enumerate(md.get("keywords", []) or []):
        out.append(f"* metadata.keyword[{i}] = {fsh_str(kw)}")
    for i, au in enumerate(md.get("authors", []) or []):
        out.append(f"* metadata.author[{i}] = {fsh_str(au)}")
    if md.get("endorsing_authority"):
        out.append(f"* metadata.endorsingAuthority = {fsh_str(md['endorsing_authority'])}")
    out.append(f"* metadata.versionNumber = {fsh_str(md.get('version_number', '0.0.0'))}")
    out.append(f"* metadata.creationDate = {fsh_str(str(md.get('creation_date', '')))}")
    if md.get("publication_date"):
        out.append(f"* metadata.publicationDate = {fsh_str(str(md['publication_date']))}")
    if md.get("expiration_date"):
        out.append(f"* metadata.expirationDate = {fsh_str(str(md['expiration_date']))}")
    if md.get("next_revision_date"):
        out.append(f"* metadata.nextRevisionDate = {fsh_str(str(md['next_revision_date']))}")
    out.append(f"* metadata.publicationStatus = {fsh_code(md.get('publication_status', 'AuthorDraft'))}")
    if md.get("publisher"):
        out.append(f"* metadata.publisher = {fsh_str(md['publisher'])}")
    for i, lg in enumerate(md.get("language", []) or []):
        out.append(f"* metadata.language[{i}] = {fsh_code(lg)}")
    if md.get("license"):
        out.append(f"* metadata.license = {fsh_str(md['license'])}")

    pr = doc.get("provenance") or {}
    out.append("")
    out.append("// --- Provenance ---")
    out.append(f"* provenance.createdBy = {fsh_str(pr.get('created_by', ''))}")
    for i, rv in enumerate(pr.get("reviewers", []) or []):
        out.append(f"* provenance.reviewer[{i}] = {fsh_str(rv)}")
    if pr.get("git_commit"):
        out.append(f"* provenance.gitCommit = {fsh_str(pr['git_commit'])}")

    for i, issue in enumerate(doc.get("issues", []) or []):
        out.append(f"* issue[{i}] = {fsh_str(issue)}")
    for i, rel in enumerate(doc.get("related_elements", []) or []):
        out.append(f"* relatedElement[{i}].relation = {fsh_code(rel['relation'])}")
        out.append(f"* relatedElement[{i}].target = {fsh_str(rel['target'])}")

    return "\n".join(out) + "\n"


# ============================================================================
# Main
# ============================================================================

README_TEXT = '''# FHIR Logical Model — Distributions-Artefakte (autogeneriert)

Dieser Ordner ist **autogeneriert** durch `scripts/build-fhir-logical-models.py` und
über `.gitignore` aus der Versionskontrolle ausgeschlossen.

Single Source of Truth bleibt `elements/<phase>/*.yaml`.

Hintergrund-Doku (archiviert): `MiHUB Patientenpfad/.archive/fhir-logical-model/`.

## Struktur

```
_schema/
├── base-data-element.fsh           ← Logical Model (kind=logical, Parent=Base)
└── codesystems-valuesets.fsh      ← CodeSystems + ValueSets

instances/<phase>/
└── <name>.fsh                     ← Instance of BaseDataElement
```

## Sushi-/IG-Publisher-Workflow (optional)

```bash
# 1. Sushi-Projekt-Skelett anlegen
sushi --init  # oder vorhandenes sushi-config.yaml verwenden

# 2. FSH-Dateien einbinden
ln -s <out>/_schema input/fsh/
ln -s <out>/instances input/fsh/

# 3. Build
sushi .          # erzeugt fsh-generated/resources/*.json
ig-publisher --ig ig.json
```
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--out",
        default=str(ROOT / "derived" / "fhir-logical-model"),
        help="Zielordner (Default: derived/fhir-logical-model unter Repo-Wurzel)",
    )
    parser.add_argument(
        "--namespace-base",
        default="https://mihub.de/fhir",
        help=("FHIR-Canonical-URL-Basis für CodeSystems/ValueSets/Logical-Model. "
              "Default 'https://mihub.de/fhir'. Beispiel: "
              "'https://example.org/data-elements/fhir' für ein anderes Projekt."),
    )
    parser.add_argument(
        "--title",
        default="MiHUB Patientenpfad — Datenelement-Spezifikation",
        help=("Titel des Logical Models (Project-Branding). Default ist der MiHUB-Titel."),
    )
    args = parser.parse_args()
    out_root = Path(args.out)
    schema_dir = out_root / "_schema"
    instances_dir = out_root / "instances"
    schema_dir.mkdir(parents=True, exist_ok=True)
    instances_dir.mkdir(parents=True, exist_ok=True)

    # 1. Schema-Files (embedded) — projekt-spezifisch parametrisiert
    namespace_base = args.namespace_base.rstrip("/")
    logical_fsh = LOGICAL_MODEL_FSH.replace("{NAMESPACE_BASE}", namespace_base)
    # Title-Replacement: vorhandener Default-Title wird durch CLI-Wert ersetzt
    logical_fsh = logical_fsh.replace(
        'Title: "MiHUB Patientenpfad — Datenelement-Spezifikation"',
        f'Title: "{args.title}"',
    )
    valuesets_fsh = VALUESETS_FSH.replace("{NAMESPACE_BASE}", namespace_base)
    # Auch SYSTEM_URL local-no-standard-binding-Mapping aktualisieren (für Instances)
    SYSTEM_URL["local-no-standard-binding"] = (
        f"{namespace_base}/CodeSystem/local-no-standard-binding"
    )

    (schema_dir / "base-data-element.fsh").write_text(logical_fsh, encoding="utf-8")
    (schema_dir / "codesystems-valuesets.fsh").write_text(valuesets_fsh, encoding="utf-8")
    (out_root / "README.md").write_text(README_TEXT, encoding="utf-8")

    # 2. Instances aus YAMLs
    files = sorted(ELEMS.glob("*/*.yaml"))
    for fp in files:
        with fp.open(encoding="utf-8") as f:
            doc = yaml.safe_load(f)
        phase_dir = instances_dir / fp.parent.name
        phase_dir.mkdir(parents=True, exist_ok=True)
        (phase_dir / (fp.stem + ".fsh")).write_text(render_instance(doc), encoding="utf-8")

    print(f"Wrote FHIR Logical Model artifacts to {out_root}")
    print(f"  _schema/base-data-element.fsh           (Logical Model)")
    print(f"  _schema/codesystems-valuesets.fsh      (CodeSystems + ValueSets)")
    print(f"  instances/                             ({len(files)} FSH instances)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
